version: '3'
services: 
    web:
        image: docker-node-mongo
        build: .
        command: "node server.js"
        ports: 
            - "5000:3000"
        depends_on: 
            - "mongo"
    mongo:
        image: mongo
        ports: 
            - "27017:27017"